### ISSUE TITLE
Can't seem to get the {% with %} syntax working

### ISSUE THREAD

**Issue by mitdemrad** [jonbretman/jinja-to-js#26]
Thanks for the awesome library:

I was having some trouble getting {% with %}{% endwith %} to work. I even grabbed the test case out of the projects template directory (with.jinja). 

Here is the command I ran:

jinja_to_js ./templates with.jinja -m es6 -o ./js/with_jinja.js
Traceback (most recent call last):
  File "/usr/local/bin/jinja_to_js", line 9, in <module>
    load_entry_point('jinja-to-js==3.1.0', 'console_scripts', 'jinja_to_js')()
  File "/Library/Python/2.7/site-packages/jinja_to_js/__main__.py", line 92, in main
    compiler = JinjaToJS(**get_init_kwargs(options))
  File "/Library/Python/2.7/site-packages/jinja_to_js/__init__.py", line 245, in __init__
    self._process_node(node)
  File "/Library/Python/2.7/site-packages/jinja_to_js/__init__.py", line 306, in _process_node
    raise Exception('Unknown node %s' % node)
Exception: Unknown node With(targets=[], values=[], body=[Output(nodes=[TemplateData(da etc...

Am i doing something wrong? Thanks a lot!

**Comment by lystcontractor** [comment]
@public I think this issue is fixed by our PR

**Comment by lystcontractor** [comment]
@jonbretman I think this is fixed by the PR I submitted (pair coded with @public)

**Comment by mitdemrad** [comment]
I verified that the issue is fixed thanks!
